[package]
name = "cli-trader"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5.4", default-features = false, features = ["contract", "network", "providers", "reqwest", "signers"] }
alloy-chains = "0.1.44"
alloy-contract = "0.5.4"
alloy-signer-local = "0.5.4"
alloy-sol-types = { version = "0.8.10", features = ["json"] }
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
clap-repl = "0.3.0"
comfy-table = "7.1.1"
hex = "0.4.3"
prost = "0.13.3"
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["rt-multi-thread"] }
tonic = { version = "0.12.3", default-features = false, features = ["codegen", "prost", "transport"] }
url = "2.5.2"

[build-dependencies]
tonic-build = "0.12.3"
